name: github action cicd pipeline 
on:
    push:
        branches:
        - main

jobs:
    cicdtest:
        runs-on: ubuntu-latest
        steps:
        - name: checkout-code
          uses: actions/checkout@v2
        - name: Docker build and push Docker image
          run: | 
            docker build -t myimageactionproj .
            echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
            docker tag myimageactionproj ${{secrets.DOCKERHUB_USERNAME}}/myimageactionproj
            docker push ${{secrets.DOCKERHUB_USERNAME}}/myimageactionproj
        - name: setup SSH key
          run: |
            echo "${{secrets.EC2_PRIVATE_KEY}}" > /tmp/ssh_key
            chmod 600 /tmp/ssh_key
        
        - name: connect to EC2
          run: |
           ssh -o "StrictHostKeyChecking=no" -i /tmp/ssh_key ubuntu@3.83.223.28 
           "
           kubectl delete deployment my-deployment
           kubectl apply -f /home/ubuntu/my-action-deployment.yml
           "
        
