name: github action cicd pipeline 
on:
    push:
        branches:
        - main

jobs:
    cicdtest:
        runs-on: ubuntu-latest
        steps:
        - name: checkout-code
          uses: actions/checkout@v2
        - name: Docker build and push Docker image
          run: | 
            docker build -t myimageactionproj .
            echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} -password--stdin
            docker tag myimage ${{secrets.DOCKERHUB_USERNAME}}/myimageactionproj
            docker push ${{secrets.DOCKERHUB_USERNAME}}/myimageactionproj
        
